replicaCount: 1
namespaceOverride : mesh-observability
image:
  repository: "prom/prometheus"
  pullPolicy: Always
  tag: v2.35.0
#Fromt the link- https://github.com/kumahq/kuma/blob/8692e9528e00a059cb08d7f47b91f222758b879e/app/kumactl/cmd/install/context/install_observability_context.go
KumaCpAddress: "http://kuma-control-plane.kuma-system:5676"

component: "server"
name: "prometheus-server"
imagePullSecrets: []
nameOverride: "prometheus"
fullnameOverride: "prometheus-server"
namespace: "mesh-observability"
#Please provide IAM role and the url for remoteWrite
iamRole: "IAMROLE-TO-BE-DECLARED"
remoteWrite:
  enabled: true
  url: https://aps-workspaces.ap-northeast-1.amazonaws.com/workspaces/ws-xxxxxxxxxxx-yyyyyy-zzzzzzzz/api/v1/remote_write
  region: ap-northeast-1
  queue_config:
    max_samples_per_send: 1000
    max_shards: 200
    capacity: 2500
storage: "12Gi"
service:
  enabled: true
  annotations:
    author: "parjun8840"
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  type: ""
  ports:
    http:
      port: 80
      targetPort: 9090
      protocol: TCP
podAnnotations: {}
resources: {}
nodeSelector: {}
