apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: {{ .Values.component }}
    app: {{ template "name" . }}
  name: {{ template "fullname" . }}
  namespace: {{ template "app.namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
