apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: {{ .Values.component }}
    app: {{ template "name" . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.iamRole }}
  name: {{ template "fullname" . }}
  namespace: {{ .Values.namespace }}
